version: '3'
services:
  stt_en:
    build:
      context: stt
      dockerfile: Dockerfile.kaldi.en
    ports:
      - "3070:80"
  stt_de:
    build:
      context: stt
      dockerfile: Dockerfile.kaldi.de
    ports:
      - "3071:80"
  tts:
    build:
      context: tts
    ports:
      - "3080:59125"
